import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import GoogleAnalyticsBody from "./GoogleAnalyticsBody";
import GoogleAnalyticsHead from "./GoogleAnalyticsHead";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});

// const poppins = localFont({
//   src: "font_file",
//   variable: "--font--poppins",
//   // Now after variable, there will be no font family, there will be custom font
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    // It is used when we share our pages on Social Media
    title: "...",
    description: "...",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleAnalyticsHead />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={poppins.variable}
      >
        <GoogleAnalyticsBody />
        {children}
      </body>
    </html>
  );
}
